namespace KChannelAdvisor.Descriptor.BulkUploader
{
    internal class KCHeaders
    {
        public const string AuctionTitle = "Auction Title";
        public const string InventoryNumber = "Inventory Number";
        public const string QuantityUpdateType = "Quantity Update Type";
        public const string Quantity = "Quantity";
        public const string DCQuantity = "DC Quantity";
        public const string DCQuantityUpdateType = "DC Quantity Update Type";
        public const string BundleComponents = "Bundle Components";
        public const string BundleDCs = "Bundle DCs";
        public const string BlockExternalQuantity = "Block External Quantity";
        public const string StartingBid = "Starting Bid";
        public const string Reserve = "Reserve";
        public const string Weight = "Weight";
        public const string ISBN = "ISBN";
        public const string UPC = "UPC";
        public const string EAN = "EAN";
        public const string ASIN = "ASIN";
        public const string MPN = "MPN";
        public const string ShortDescription = "Short Description";
        public const string Description = "Description";
        public const string Manufacturer = "Manufacturer";
        public const string Brand = "Brand";
        public const string Condition = "Condition";
        public const string Warranty = "Warranty";
        public const string Flag = "Flag";
        public const string FlagDescription = "FlagDescription";
        public const string SellerCost = "Seller Cost";
        public const string EstimatedShippingCost = "Estimated Shipping Cost";
        public const string ProductMargin = "Product Margin";
        public const string BuyItNowPrice = "Buy It Now Price";
        public const string RetailPrice = "Retail Price";
        public const string SecondChanceOfferPrice = "Second Chance Offer Price";
        public const string MinimumPrice = "Minimum Price";
        public const string MaximumPrice = "Maximum Price";
        public const string PictureURLs = "Picture URLs";
        public const string TaxProductCode = "TaxProductCode";
        public const string SupplierCode = "Supplier Code";
        public const string SupplierPO = "Supplier PO";
        public const string WarehouseLocation = "Warehouse Location";
        public const string ReceivedInInventory = "Received In Inventory";
        public const string InventorySubtitle = "Inventory Subtitle";
        public const string RelationshipName = "Relationship Name";
        public const string VariationParentSKU = "VariationParent SKU";
        public const string Labels = "Labels";
        public const string DCCode = "DC Code";
        public const string DoNotConsolidate = "Do Not Consolidate";
        public const string MultipackQuantity = "Multipack Quantity";
        public const string Classification = "Classification";
        public const string AttributeName_F = "Attribute{0}Name";
        public const string AttributeValue_F = "Attribute{0}Value";
        public const string DefaultPackageName = "Default Package Name";
        public const string HarmonizedCode = "Harmonized Code";
        public const string Height = "Height";
        public const string Length = "Length";
        public const string Width = "Width";
        public const string ShipZoneName = "Ship Zone Name";
        public const string ShipCarrierCode = "Ship Carrier Code";
        public const string ShipClassCode = "Ship Class Code";
        public const string ShipRateFirstItem = "Ship Rate First Item";
        public const string ShipHandlingFirstItem = "Ship Handling First Item";
        public const string ShipRateAdditionalItem = "Ship Rate Additional Item";
        public const string ShipHandlingAdditionalItem = "Ship Handling Additional Item";
        public const string ShipRepeat = "(repeat)";
        public const string StorePrice = "ChannelAdvisor Store Price";
    }
}
